import type { TestCase } from '../types/nova';

export const NOVA_TEST_SUITE: TestCase[] = [
  // 1. Basic Spatial Commands
  {
    id: 'basic-1',
    category: 'Basic spatial commands',
    prompt: 'Move Browser left.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'browser',
    description: 'Translates directional "left" to MOVE command targeting browser with relation: left',
  },
  {
    id: 'basic-2',
    category: 'Basic spatial commands',
    prompt: 'Move Terminal right.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'terminal',
    description: 'Translates directional "right" to MOVE command targeting terminal with relation: right',
  },
  {
    id: 'basic-3',
    category: 'Basic spatial commands',
    prompt: 'Move Code to the center.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'code',
    description: 'Translates position "center" to MOVE command targeting code with relation: center',
  },

  // 2. Resize
  {
    id: 'resize-1',
    category: 'Resize',
    prompt: 'Make Browser bigger.',
    expectedStatus: 'ok',
    expectedActions: ['RESIZE'],
    expectedTarget: 'browser',
    description: 'Normalizes "bigger" to standard scale multiplier 1.2',
  },
  {
    id: 'resize-2',
    category: 'Resize',
    prompt: 'Make Code slightly smaller.',
    expectedStatus: 'ok',
    expectedActions: ['RESIZE'],
    expectedTarget: 'code',
    description: 'Normalizes "slightly smaller" to scale 0.9',
  },
  {
    id: 'resize-3',
    category: 'Resize',
    prompt: 'Make Terminal much bigger.',
    expectedStatus: 'ok',
    expectedActions: ['RESIZE'],
    expectedTarget: 'terminal',
    description: 'Normalizes "much bigger" to scale 1.4',
  },

  // 3. Focus & Depth
  {
    id: 'focus-1',
    category: 'Focus',
    prompt: 'Focus Browser.',
    expectedStatus: 'ok',
    expectedActions: ['FOCUS'],
    expectedTarget: 'browser',
    description: 'Direct focus request targeting browser',
  },
  {
    id: 'focus-2',
    category: 'Focus',
    prompt: 'Bring Code forward.',
    expectedStatus: 'ok',
    expectedActions: ['BRING_FORWARD'],
    expectedTarget: 'code',
    description: 'Z-depth elevation command BRING_FORWARD for code',
  },
  {
    id: 'focus-3',
    category: 'Focus',
    prompt: 'Send Terminal back.',
    expectedStatus: 'ok',
    expectedActions: ['SEND_BACK'],
    expectedTarget: 'terminal',
    description: 'Z-depth recession command SEND_BACK for terminal',
  },

  // 4. Contextual Pronouns
  {
    id: 'context-1',
    category: 'Context',
    prompt: 'Make this bigger.',
    contextOverride: { focusedWindow: 'code' },
    expectedStatus: 'ok',
    expectedActions: ['RESIZE'],
    expectedTarget: 'code',
    description: 'Resolves pronoun "this" to currently focused window (code)',
  },
  {
    id: 'context-2',
    category: 'Context',
    prompt: 'Move this left.',
    contextOverride: { focusedWindow: 'browser' },
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'browser',
    description: 'Resolves "this" to active focused window (browser)',
  },
  {
    id: 'context-3',
    category: 'Context',
    prompt: 'Bring that forward.',
    contextOverride: { focusedWindow: 'terminal' },
    expectedStatus: 'ok',
    expectedActions: ['BRING_FORWARD'],
    expectedTarget: 'terminal',
    description: 'Resolves contextual demonstrative "that" to active window target',
  },

  // 5. Relative Relationships
  {
    id: 'rel-1',
    category: 'Relative relationships',
    prompt: 'Put Browser beside Code.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'browser',
    description: 'Positions browser with relation: beside, relativeTo: code',
  },
  {
    id: 'rel-2',
    category: 'Relative relationships',
    prompt: 'Move Terminal behind Code.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'terminal',
    description: 'Positions terminal with relation: behind, relativeTo: code',
  },
  {
    id: 'rel-3',
    category: 'Relative relationships',
    prompt: 'Put Notes above Browser.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE'],
    expectedTarget: 'notes',
    description: 'Positions notes with relation: above, relativeTo: browser',
  },

  // 6. Multi-Command Requests
  {
    id: 'multi-1',
    category: 'Multi-command',
    prompt: 'Move Browser left and make Code bigger.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE', 'RESIZE'],
    description: 'Sequential compound command: MOVE browser left, RESIZE code',
  },
  {
    id: 'multi-2',
    category: 'Multi-command',
    prompt: 'Put Terminal on the right and bring Code forward.',
    expectedStatus: 'ok',
    expectedActions: ['MOVE', 'BRING_FORWARD'],
    description: 'Compound command: MOVE terminal right, BRING_FORWARD code',
  },
  {
    id: 'multi-demo',
    category: 'Multi-command',
    prompt:
      "I'm working on development. Put the browser on my left, make Code slightly bigger, bring Terminal forward, and then switch to the Development workspace.",
    expectedStatus: 'ok',
    expectedActions: ['MOVE', 'RESIZE', 'BRING_FORWARD', 'SWITCH_WORKSPACE'],
    description: 'Section 32 Final Demonstration benchmark phrase',
  },

  // 7. Workspace Commands
  {
    id: 'ws-1',
    category: 'Workspace',
    prompt: 'Switch to Development.',
    expectedStatus: 'ok',
    expectedActions: ['SWITCH_WORKSPACE'],
    expectedTarget: 'development',
    description: 'Switches workspace to development',
  },
  {
    id: 'ws-2',
    category: 'Workspace',
    prompt: 'Go to Study.',
    expectedStatus: 'ok',
    expectedActions: ['SWITCH_WORKSPACE'],
    expectedTarget: 'study',
    description: 'Switches workspace to study',
  },
  {
    id: 'ws-3',
    category: 'Workspace',
    prompt: 'Take me home.',
    expectedStatus: 'ok',
    expectedActions: ['SWITCH_WORKSPACE'],
    expectedTarget: 'home',
    description: 'Interprets "Take me home" as SWITCH_WORKSPACE to home',
  },

  // 8. Ambiguous
  {
    id: 'ambig-1',
    category: 'Ambiguous',
    prompt: 'Move that.',
    contextOverride: { focusedWindow: null },
    expectedStatus: 'needs_clarification',
    description: 'Insufficient context: "Move that" with no target specified requires clarification',
  },
  {
    id: 'ambig-2',
    category: 'Ambiguous',
    prompt: 'Put it there.',
    expectedStatus: 'needs_clarification',
    description: 'Completely ambiguous target and location requires clarification',
  },
  {
    id: 'ambig-3',
    category: 'Ambiguous',
    prompt: 'Make it bigger.',
    contextOverride: { focusedWindow: null },
    expectedStatus: 'needs_clarification',
    description: 'Ambiguous target "it" when no window has focus asks for clarification',
  },

  // 9. Unsupported
  {
    id: 'unsupp-1',
    category: 'Unsupported',
    prompt: 'Open Spotify.',
    expectedStatus: 'unsupported',
    description: 'Non-NOVA desktop application request returns unsupported status',
  },
  {
    id: 'unsupp-2',
    category: 'Unsupported',
    prompt: 'Run this command in Terminal.',
    expectedStatus: 'unsupported',
    description: 'Arbitrary shell execution blocked by security boundary',
  },
  {
    id: 'unsupp-3',
    category: 'Unsupported',
    prompt: 'Delete my files.',
    expectedStatus: 'unsupported',
    description: 'Destructive filesystem manipulation forbidden',
  },
  {
    id: 'unsupp-4',
    category: 'Unsupported',
    prompt: 'Turn off Wi-Fi.',
    expectedStatus: 'unsupported',
    description: 'System-level hardware toggles are unsupported by NOVA',
  },

  // 10. Edge Cases
  {
    id: 'edge-1',
    category: 'Edge cases',
    prompt: 'Move Calculator to the left.',
    expectedStatus: 'unsupported',
    description: 'Nonexistent window identifier fails safely',
  },
  {
    id: 'edge-2',
    category: 'Edge cases',
    prompt: '   ',
    expectedStatus: 'invalid',
    description: 'Empty whitespace input rejected cleanly with status invalid',
  },
  {
    id: 'edge-3',
    category: 'Edge cases',
    prompt: 'Switch to the Mars colony workspace.',
    expectedStatus: 'unsupported',
    description: 'Invalid/nonexistent workspace name returns unsupported message',
  },
];
